/**
 * The log files of one run, under `<runDir>/logs`, and the one bounded reading
 * of them.
 *
 * Three kinds, and nothing else: `run.log`, one append-only human-readable
 * timeline of the run's meaningful state changes; one
 * `.stdout.log`/`.stderr.log` pair per configured command invocation; and one
 * `agent-*.log` per top-level coding turn. Files are created exclusively and
 * only appended to afterwards, so evidence from an earlier invocation or turn
 * is never truncated or overwritten. `readCommandOutput` is the only reading
 * here: the failure output a repair turn is given. The files decide the run's
 * evidence, and the copy handed to a turn never replaces them.
 */
import { createWriteStream } from 'node:fs';
import { ReportError } from './errors.js';
import type { WriteStream } from 'node:fs';
import { appendFile, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { messageOf } from '../shared/errors.js';
import type { CommandResult } from '../shared/types.js';

/** Name of the append-only lifecycle timeline inside `logs/`. */
const RUN_LOG_NAME = 'run.log';
/**
 * Log file names are generated by the harness, but a value that could be read
 * as a path is refused rather than rewritten: a label never decides where a run
 * writes.
 */
const LOG_LABEL_PATTERN = /^[A-Za-z0-9][A-Za-z0-9_.-]{0,63}$/;

/** The lifecycle timeline of a run: `<logsDir>/run.log`. */
export function runLogPath(logsDir: string): string {
  return path.join(logsDir, RUN_LOG_NAME);
}

/**
 * Appends one timestamped line to the run timeline, creating the file when it
 * does not exist yet. Earlier lines are never rewritten, so the timeline reads
 * in the order the run produced it.
 */
export async function appendRunLog(runLog: string, message: string): Promise<void> {
  if (message.trim() === '' || /[\r\n]/.test(message)) {
    throw new ReportError(
      `"${message}" is not a usable timeline message. The timeline holds one line per state ` +
        'change, so a message must be nonblank and must not contain a line break.',
    );
  }

  try {
    await appendFile(runLog, `${new Date().toISOString()} ${message}\n`, 'utf8');
  } catch (cause) {
    throw new ReportError(
      `the run timeline "${runLog}" could not be appended to: ${messageOf(cause)}`,
      { cause },
    );
  }
}

/** The two output files of one configured command invocation. */
export interface CommandLog {
  readonly stdoutPath: string;
  readonly stderrPath: string;
  /** Adds a chunk of the command's standard output. */
  writeStdout(chunk: string): void;
  /** Adds a chunk of the command's standard error. */
  writeStderr(chunk: string): void;
  /**
   * Flushes and closes both files. Rejects with a {@link ReportError} when the
   * output could not be written: a result whose evidence was lost must not be
   * reported as a usable one.
   */
  close(): Promise<void>;
}

/**
 * Creates one file exclusively, so a file that is already there is never
 * overwritten. `whenTaken` says what the taken name means for the caller.
 */
async function createFileExclusively(file: string, whenTaken: string): Promise<void> {
  try {
    await writeFile(file, '', { flag: 'wx' });
  } catch (cause) {
    if ((cause as NodeJS.ErrnoException).code === 'EEXIST') {
      throw new ReportError([`"${file}" already exists.`, whenTaken].join('\n'), { cause });
    }
    throw new ReportError(`"${file}" could not be created: ${messageOf(cause)}`, { cause });
  }
}

/** Why a taken command-log name is refused rather than reused. */
const COMMAND_LOG_TAKEN = [
  'A command name is used once per run, and the logs of earlier commands are kept as they',
  'are: they are never truncated or overwritten.',
].join('\n');

/** Resolves when the stream has finished and closed, or already had. */
function endStream(stream: WriteStream): Promise<void> {
  return new Promise((resolve) => {
    if (stream.closed || stream.destroyed) {
      resolve();
      return;
    }
    stream.once('close', () => resolve());
    stream.end();
  });
}

/**
 * Creates the output files of one command invocation: `<label>.stdout.log` and
 * `<label>.stderr.log` in `logsDir`. The caller writes the command's output
 * into them and closes them before reading the result.
 */
export async function openCommandLog(logsDir: string, label: string): Promise<CommandLog> {
  if (!LOG_LABEL_PATTERN.test(label)) {
    throw new ReportError(
      [
        `"${label}" is not a usable log label.`,
        'A label is a short name of letters, digits, "_", "-", and "." that identifies this',
        "invocation's two log files. It never names a path, so it cannot decide where a run writes.",
      ].join('\n'),
    );
  }

  const stdoutPath = path.join(logsDir, `${label}.stdout.log`);
  const stderrPath = path.join(logsDir, `${label}.stderr.log`);
  await createFileExclusively(stdoutPath, COMMAND_LOG_TAKEN);
  await createFileExclusively(stderrPath, COMMAND_LOG_TAKEN);

  const streams: WriteStream[] = [];
  let failed: string | null = null;

  // Writes happen while the command runs, so a stream error is remembered for
  // close() instead of becoming an unhandled 'error' event.
  const appendStream = (file: string): WriteStream => {
    const stream = createWriteStream(file, { flags: 'a', encoding: 'utf8' });
    stream.on('error', (cause: unknown) => {
      failed ??= messageOf(cause);
    });
    streams.push(stream);
    return stream;
  };

  const stdout = appendStream(stdoutPath);
  const stderr = appendStream(stderrPath);
  let closed = false;

  return {
    stdoutPath,
    stderrPath,
    writeStdout: (chunk: string) => {
      stdout.write(chunk);
    },
    writeStderr: (chunk: string) => {
      stderr.write(chunk);
    },
    close: async () => {
      if (closed) {
        return;
      }
      closed = true;
      await Promise.all(streams.map(endStream));
      if (failed !== null) {
        throw new ReportError(
          `the output of "${label}" could not be written to "${logsDir}": ${failed}`,
        );
      }
    },
  };
}

/** How much of one output file a repair turn is given, in characters. */
const OUTPUT_EXCERPT_LIMIT = 4000;

/** Marks an excerpt that left earlier output out. */
const OUTPUT_OMITTED = '… (earlier output omitted)\n';

/** What an invocation that wrote nothing is recorded as, in feedback. */
const OUTPUT_EMPTY = '(no output was written)';

/**
 * The end of one log file, bounded. The end is the interesting part: a command
 * reports the failure after the work that led to it. A file this run's own
 * command wrote and that cannot be read now contributes nothing — the path is
 * still recorded in the command result, so nothing is hidden by that.
 */
async function readOutputTail(file: string): Promise<string> {
  let text: string;
  try {
    text = await readFile(file, 'utf8');
  } catch {
    return '';
  }
  if (text.length <= OUTPUT_EXCERPT_LIMIT) {
    return text.trimEnd();
  }
  return OUTPUT_OMITTED + text.slice(text.length - OUTPUT_EXCERPT_LIMIT).trimEnd();
}

/**
 * What one command invocation wrote, as far as it was recorded: its standard
 * output and its standard error, each labelled with the log file it came from and
 * bounded to the end of that file. This is the failure output a repair turn is
 * given (docs/spec.md §2). It is a copy for that turn; the files themselves stay
 * where they are, unchanged.
 */
export async function readCommandOutput(result: CommandResult): Promise<string> {
  const stdout = await readOutputTail(result.stdoutPath);
  const stderr = await readOutputTail(result.stderrPath);
  return [
    `stdout (${result.stdoutPath}):`,
    stdout === '' ? OUTPUT_EMPTY : stdout,
    `stderr (${result.stderrPath}):`,
    stderr === '' ? OUTPUT_EMPTY : stderr,
  ].join('\n');
}

/** Why a taken agent-log name is refused rather than reused. */
const AGENT_LOG_TAKEN = [
  'Each top-level coding turn writes its own agent log, and the output of an earlier turn is',
  'kept as it is: it is never truncated or overwritten.',
].join('\n');

/** The file holding the useful output of one top-level coding turn. */
export interface AgentLog {
  /** The file this turn's output goes to. Referenced by the report, never copied in. */
  readonly path: string;
  /** Adds a chunk of the agent's useful output. */
  write(chunk: string): void;
  /**
   * Flushes and closes the file. Rejects with a {@link ReportError} when the
   * output could not be written: a turn whose evidence was lost must not be
   * reported as a usable one.
   */
  close(): Promise<void>;
}

/**
 * Turns are counted from 1: turn 1 is the implementation, and every turn after
 * it is a repair. A turn number is generated by the caller's own loop, so a
 * value that could name something else is refused rather than used.
 */
function assertUsableTurn(turn: number): void {
  if (Number.isInteger(turn) && turn >= 1) {
    return;
  }
  throw new ReportError(
    `"${String(turn)}" is not a usable coding turn: turns are counted from 1, where turn 1 is the ` +
      'implementation and the repair turns follow it.',
  );
}

/**
 * The agent log of top-level coding turn `turn`: `agent-implementation.log` for
 * the implementation, then `agent-repair-1.log`, `agent-repair-2.log`, … for the
 * repairs. Each turn has its own file, so no turn can overwrite another's
 * output, and the report points at these files instead of holding transcripts.
 */
export function agentLogPath(logsDir: string, turn: number): string {
  assertUsableTurn(turn);
  const name = turn === 1 ? 'agent-implementation' : `agent-repair-${String(turn - 1)}`;
  return path.join(logsDir, `${name}.log`);
}

/**
 * Creates the log of one coding turn. The caller writes the turn's useful output
 * into it and closes it, and keeps the returned path for the report.
 */
export async function openAgentLog(logsDir: string, turn: number): Promise<AgentLog> {
  const file = agentLogPath(logsDir, turn);
  await createFileExclusively(file, AGENT_LOG_TAKEN);

  const stream = createWriteStream(file, { flags: 'a', encoding: 'utf8' });
  let failed: string | null = null;
  stream.on('error', (cause: unknown) => {
    failed ??= messageOf(cause);
  });
  let closed = false;

  return {
    path: file,
    write: (chunk: string) => {
      stream.write(chunk);
    },
    close: async () => {
      if (closed) {
        return;
      }
      closed = true;
      await endStream(stream);
      if (failed !== null) {
        throw new ReportError(
          `the agent output of coding turn ${String(turn)} could not be written to "${file}": ${failed}`,
        );
      }
    },
  };
}
