/**
 * What one run writes into its own directory: the logs under
 * `<runDir>/logs` and the final `<runDir>/result.json`.
 *
 * The logs come in three kinds, and nothing else:
 *
 * - `run.log`, one append-only human-readable timeline of the run's meaningful
 *   state changes (preparation, baseline, agent turns, check rounds, repairs,
 *   cancellation, final status). It is a debugging aid, not a logging
 *   subsystem: no levels, no structured events, no log library. Command output
 *   is never copied into it.
 * - One `.stdout.log`/`.stderr.log` pair per configured command invocation, so
 *   each command's output stays separate, identifiable, and complete.
 * - One `agent-*.log` per top-level coding turn, so the useful output of each
 *   turn is kept where it was produced and an earlier turn is never overwritten.
 *
 * Files are created exclusively and only appended to afterwards: evidence from
 * an earlier invocation or turn is never truncated or overwritten.
 *
 * {@link writeRunReport} writes the readable final `result.json`: what the run
 * was, what every attempt did, and how it ended. It carries the evidence in the
 * same shape the run observed it in, and it points at the log files rather than
 * copying their contents, so a report stays small enough to read and the bulk of
 * the output stays in the files that hold it. It is written once, and only for a
 * run that got as far as a run directory: an invocation refused before that has
 * nothing to report and is a CLI error instead. See docs/spec.md §§3–5.
 */

import { createWriteStream } from 'node:fs';
import { appendFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import type { WriteStream } from 'node:fs';
import type {
  AttemptEvidence,
  AttemptKind,
  CheckRoundResult,
  RunReport,
  RunStatus,
  WorkspaceReport,
} from './types.js';
import type { PreparedWorkspace, RunDirectory, SourcePreflight } from './workspace.js';

/** A log file that could not be created, written, or appended to. */
export class ReportError extends Error {
  constructor(message: string, options?: { cause?: unknown }) {
    super(message, options);
    this.name = 'ReportError';
  }
}

/** Name of the append-only lifecycle timeline inside `logs/`. */
const RUN_LOG_NAME = 'run.log';

/** Name of the final report inside the run directory. */
const RUN_REPORT_NAME = 'result.json';

/**
 * Log file names are generated by the harness, but a value that could be read
 * as a path is refused rather than rewritten: a label never decides where a run
 * writes.
 */
const LOG_LABEL_PATTERN = /^[A-Za-z0-9][A-Za-z0-9_.-]{0,63}$/;

function messageOf(cause: unknown): string {
  return cause instanceof Error ? cause.message : String(cause);
}

/** The lifecycle timeline of a run: `<logsDir>/run.log`. */
export function runLogPath(logsDir: string): string {
  return path.join(logsDir, RUN_LOG_NAME);
}

/**
 * Appends one timestamped line to the run timeline, creating the file when it
 * does not exist yet. Earlier lines are never rewritten, so the timeline reads
 * in the order the run produced it.
 */
export async function appendRunLog(runLog: string, message: string): Promise<void> {
  if (message.trim() === '' || /[\r\n]/.test(message)) {
    throw new ReportError(
      `"${message}" is not a usable timeline message. The timeline holds one line per state ` +
        'change, so a message must be nonblank and must not contain a line break.',
    );
  }

  try {
    await appendFile(runLog, `${new Date().toISOString()} ${message}\n`, 'utf8');
  } catch (cause) {
    throw new ReportError(
      `the run timeline "${runLog}" could not be appended to: ${messageOf(cause)}`,
      { cause },
    );
  }
}

/** The two output files of one configured command invocation. */
export interface CommandLog {
  readonly stdoutPath: string;
  readonly stderrPath: string;
  /** Adds a chunk of the command's standard output. */
  writeStdout(chunk: string): void;
  /** Adds a chunk of the command's standard error. */
  writeStderr(chunk: string): void;
  /**
   * Flushes and closes both files. Rejects with a {@link ReportError} when the
   * output could not be written: a result whose evidence was lost must not be
   * reported as a usable one.
   */
  close(): Promise<void>;
}

/**
 * Creates one file exclusively, so a file that is already there is never
 * overwritten. `whenTaken` says what the taken name means for the caller.
 */
async function createFileExclusively(file: string, whenTaken: string): Promise<void> {
  try {
    await writeFile(file, '', { flag: 'wx' });
  } catch (cause) {
    if ((cause as NodeJS.ErrnoException).code === 'EEXIST') {
      throw new ReportError([`"${file}" already exists.`, whenTaken].join('\n'), { cause });
    }
    throw new ReportError(`"${file}" could not be created: ${messageOf(cause)}`, { cause });
  }
}

/** Why a taken command-log name is refused rather than reused. */
const COMMAND_LOG_TAKEN = [
  'A command name is used once per run, and the logs of earlier commands are kept as they',
  'are: they are never truncated or overwritten.',
].join('\n');

/** Resolves when the stream has finished and closed, or already had. */
function endStream(stream: WriteStream): Promise<void> {
  return new Promise((resolve) => {
    if (stream.closed || stream.destroyed) {
      resolve();
      return;
    }
    stream.once('close', () => resolve());
    stream.end();
  });
}

/**
 * Creates the output files of one command invocation: `<label>.stdout.log` and
 * `<label>.stderr.log` in `logsDir`. The caller writes the command's output
 * into them and closes them before reading the result.
 */
export async function openCommandLog(logsDir: string, label: string): Promise<CommandLog> {
  if (!LOG_LABEL_PATTERN.test(label)) {
    throw new ReportError(
      [
        `"${label}" is not a usable log label.`,
        'A label is a short name of letters, digits, "_", "-", and "." that identifies this',
        "invocation's two log files. It never names a path, so it cannot decide where a run writes.",
      ].join('\n'),
    );
  }

  const stdoutPath = path.join(logsDir, `${label}.stdout.log`);
  const stderrPath = path.join(logsDir, `${label}.stderr.log`);
  await createFileExclusively(stdoutPath, COMMAND_LOG_TAKEN);
  await createFileExclusively(stderrPath, COMMAND_LOG_TAKEN);

  const streams: WriteStream[] = [];
  let failed: string | null = null;

  // Writes happen while the command runs, so a stream error is remembered for
  // close() instead of becoming an unhandled 'error' event.
  const appendStream = (file: string): WriteStream => {
    const stream = createWriteStream(file, { flags: 'a', encoding: 'utf8' });
    stream.on('error', (cause: unknown) => {
      failed ??= messageOf(cause);
    });
    streams.push(stream);
    return stream;
  };

  const stdout = appendStream(stdoutPath);
  const stderr = appendStream(stderrPath);
  let closed = false;

  return {
    stdoutPath,
    stderrPath,
    writeStdout: (chunk: string) => {
      stdout.write(chunk);
    },
    writeStderr: (chunk: string) => {
      stderr.write(chunk);
    },
    close: async () => {
      if (closed) {
        return;
      }
      closed = true;
      await Promise.all(streams.map(endStream));
      if (failed !== null) {
        throw new ReportError(
          `the output of "${label}" could not be written to "${logsDir}": ${failed}`,
        );
      }
    },
  };
}

/** Why a taken agent-log name is refused rather than reused. */
const AGENT_LOG_TAKEN = [
  'Each top-level coding turn writes its own agent log, and the output of an earlier turn is',
  'kept as it is: it is never truncated or overwritten.',
].join('\n');

/** The file holding the useful output of one top-level coding turn. */
export interface AgentLog {
  /** The file this turn's output goes to. Referenced by the report, never copied in. */
  readonly path: string;
  /** Adds a chunk of the agent's useful output. */
  write(chunk: string): void;
  /**
   * Flushes and closes the file. Rejects with a {@link ReportError} when the
   * output could not be written: a turn whose evidence was lost must not be
   * reported as a usable one.
   */
  close(): Promise<void>;
}

/**
 * Turns are counted from 1: turn 1 is the implementation, and every turn after
 * it is a repair. A turn number is generated by the caller's own loop, so a
 * value that could name something else is refused rather than used.
 */
function assertUsableTurn(turn: number): void {
  if (Number.isInteger(turn) && turn >= 1) {
    return;
  }
  throw new ReportError(
    `"${String(turn)}" is not a usable coding turn: turns are counted from 1, where turn 1 is the ` +
      'implementation and the repair turns follow it.',
  );
}

/**
 * The agent log of top-level coding turn `turn`: `agent-implementation.log` for
 * the implementation, then `agent-repair-1.log`, `agent-repair-2.log`, … for the
 * repairs. Each turn has its own file, so no turn can overwrite another's
 * output, and the report points at these files instead of holding transcripts.
 */
export function agentLogPath(logsDir: string, turn: number): string {
  assertUsableTurn(turn);
  const name = turn === 1 ? 'agent-implementation' : `agent-repair-${String(turn - 1)}`;
  return path.join(logsDir, `${name}.log`);
}

/**
 * Creates the log of one coding turn. The caller writes the turn's useful output
 * into it and closes it, and keeps the returned path for the report.
 */
export async function openAgentLog(logsDir: string, turn: number): Promise<AgentLog> {
  const file = agentLogPath(logsDir, turn);
  await createFileExclusively(file, AGENT_LOG_TAKEN);

  const stream = createWriteStream(file, { flags: 'a', encoding: 'utf8' });
  let failed: string | null = null;
  stream.on('error', (cause: unknown) => {
    failed ??= messageOf(cause);
  });
  let closed = false;

  return {
    path: file,
    write: (chunk: string) => {
      stream.write(chunk);
    },
    close: async () => {
      if (closed) {
        return;
      }
      closed = true;
      await endStream(stream);
      if (failed !== null) {
        throw new ReportError(
          `the agent output of coding turn ${String(turn)} could not be written to "${file}": ${failed}`,
        );
      }
    },
  };
}

/**
 * The only final statuses a run has (docs/spec.md §3). Checked at run time as
 * well as in the type, because a status that arrived from somewhere untyped must
 * not become a fourth one in a report.
 */
const FINAL_STATUSES: ReadonlySet<string> = new Set(['passed', 'failed', 'cancelled']);

/** Why a taken report name is refused rather than reused. */
const REPORT_TAKEN = [
  'A run writes one final report, and an existing one is evidence of an earlier finalization:',
  'it is left exactly as it is.',
].join('\n');

/** What the caller asks a final report to record. */
export interface RunReportRequest {
  /** The allocated run directory: run ID, layout, and log directory. */
  readonly run: RunDirectory;
  /** The task the run was asked to complete, as a label. */
  readonly task: { readonly id: string; readonly title: string };
  /** The repository and committed base the run was approved against. */
  readonly source: SourcePreflight;
  /**
   * The prepared working copy, or `null` when preparation failed. The run
   * directory exists either way: preparation can fail after it was created, and
   * the report then records the facts it has and says what is missing instead of
   * describing a clone that was never made.
   */
  readonly workspace: PreparedWorkspace | null;
  /** Why there is no usable working copy; `null` exactly when `workspace` is not. */
  readonly preparationProblem: string | null;
  /** Start of the run, as an ISO timestamp. */
  readonly startedAt: string;
  /** End of the run, as an ISO timestamp. */
  readonly endedAt: string;
  /** How the run ended: one of {@link RunStatus}, and nothing else. */
  readonly status: RunStatus;
  /** Why it ended that way, in one sentence. Never blank. */
  readonly reason: string;
  /** The baseline round, or `null` when no baseline round was observed. */
  readonly baseline: CheckRoundResult | null;
  /** One entry per top-level coding turn, oldest first. */
  readonly attempts: readonly AttemptEvidence[];
}

/** Refuses a request that would describe a run other than the one that happened. */
function assertReportable(request: RunReportRequest): void {
  if (!FINAL_STATUSES.has(request.status)) {
    throw new ReportError(
      `"${String(request.status)}" is not a final run status: a run ends as "passed", "failed", or ` +
        '"cancelled", and nothing else (docs/spec.md §3).',
    );
  }

  if (request.reason.trim() === '') {
    throw new ReportError(
      'a report needs a reason: say in one sentence why the run ended the way it did.',
    );
  }

  const hasWorkspace = request.workspace !== null;
  const hasProblem = request.preparationProblem !== null;
  if (hasWorkspace === hasProblem) {
    throw new ReportError(
      hasWorkspace
        ? 'a prepared working copy and a preparation problem cannot both be recorded: the report ' +
            'would describe a working copy that also failed to be prepared.'
        : 'a report without a prepared working copy has to say why one is missing. Preparation can ' +
            'fail after the run directory exists, and the directory alone is not a working copy.',
    );
  }

  for (const [index, attempt] of request.attempts.entries()) {
    const turn = index + 1;
    const kind: AttemptKind = turn === 1 ? 'implementation' : 'repair';
    if (attempt.turn !== turn || attempt.kind !== kind) {
      throw new ReportError(
        `coding turn ${String(turn)} is not recorded as such: attempts are recorded in order, and ` +
          `turn ${String(turn)} is ${turn === 1 ? 'the implementation' : 'a repair'} (received ` +
          `turn ${String(attempt.turn)}, kind "${attempt.kind}").`,
      );
    }
    if (attempt.agentLog.trim() === '') {
      throw new ReportError(
        `coding turn ${String(turn)} has no agent log: every turn keeps its useful output in its ` +
          'own file, and the report points at it rather than copying it in.',
      );
    }
  }

  const last = request.attempts.at(-1) ?? null;
  if (request.status === 'passed' && last?.checks?.outcome !== 'passed') {
    throw new ReportError(
      [
        'a report cannot say the run passed: the checks observed after the last coding turn are not',
        'a completed green round. `passed` means every configured post-agent check exited',
        'successfully for the retained working copy (docs/spec.md §3). What the agent said about its',
        'own turn is not a check result.',
      ].join('\n'),
    );
  }
}

/** The working copy as the report records it, prepared or not. */
function workspaceReport(request: RunReportRequest): WorkspaceReport {
  const { workspace } = request;
  if (workspace === null) {
    return {
      path: request.run.workspacePath,
      prepared: false,
      branch: null,
      problem: request.preparationProblem,
    };
  }
  return {
    path: workspace.workspacePath,
    prepared: true,
    branch: workspace.branch,
    problem: null,
  };
}

/** The final report of a run: `<runDir>/result.json`. */
export function runReportPath(runDir: string): string {
  return path.join(runDir, RUN_REPORT_NAME);
}

/**
 * Writes the final report of one run and returns the file it wrote, so a caller
 * never has to guess where the report is. A report is written once: an existing
 * `result.json` is refused rather than overwritten, because it is evidence of an
 * earlier finalization.
 *
 * Everything that goes wrong here is a {@link ReportError} naming the file, and
 * nothing is returned for a report that was not written: a caller cannot
 * announce a report location that does not exist. Where the report is printed is
 * the caller's business.
 */
export async function writeRunReport(request: RunReportRequest): Promise<string> {
  const report = buildReport(request);
  const file = runReportPath(request.run.runDir);

  try {
    // `wx`: the file is created by this call, so a report that is already there
    // — evidence of an earlier finalization — is never overwritten.
    await writeFile(file, `${JSON.stringify(report, null, 2)}\n`, { flag: 'wx', encoding: 'utf8' });
  } catch (cause) {
    if ((cause as NodeJS.ErrnoException).code === 'EEXIST') {
      throw new ReportError([`"${file}" already exists.`, REPORT_TAKEN].join('\n'), { cause });
    }
    throw new ReportError(`the report "${file}" could not be written: ${messageOf(cause)}`, {
      cause,
    });
  }

  return file;
}

/** The report of one run, validated and ready to serialize. */
function buildReport(request: RunReportRequest): RunReport {
  assertReportable(request);
  return {
    runId: request.run.runId,
    task: { id: request.task.id, title: request.task.title },
    source: { path: request.source.sourceRoot, baseCommit: request.source.baseCommit },
    workspace: workspaceReport(request),
    startedAt: request.startedAt,
    endedAt: request.endedAt,
    status: request.status,
    reason: request.reason,
    repairsUsed: request.attempts.filter((attempt) => attempt.kind === 'repair').length,
    baseline: request.baseline,
    attempts: request.attempts,
    runLog: runLogPath(request.run.logsDir),
  };
}
