/**
 * What one run writes into its own directory: the logs under
 * `<runDir>/logs` and the final `<runDir>/result.json`.
 *
 * The logs come in three kinds, and nothing else:
 *
 * - `run.log`, one append-only human-readable timeline of the run's meaningful
 *   state changes (preparation, baseline, agent turns, check rounds, repairs,
 *   cancellation, final status). It is a debugging aid, not a logging
 *   subsystem: no levels, no structured events, no log library. Command output
 *   is never copied into it.
 * - One `.stdout.log`/`.stderr.log` pair per configured command invocation, so
 *   each command's output stays separate, identifiable, and complete.
 * - One `agent-*.log` per top-level coding turn, so the useful output of each
 *   turn is kept where it was produced and an earlier turn is never overwritten.
 *
 * Files are created exclusively and only appended to afterwards: evidence from
 * an earlier invocation or turn is never truncated or overwritten.
 *
 * {@link readCommandOutput} reads back one invocation's two output files, bounded,
 * for the failure output a repair turn is given. That is the only reading here:
 * the files decide the run's evidence, and the copy handed to a coding turn never
 * replaces them.
 *
 * {@link writeRunReport} writes the readable final `result.json`: what the run
 * was, what every attempt did, and how it ended. It carries the evidence in the
 * same shape the run observed it in, and it points at the log files rather than
 * copying their contents, so a report stays small enough to read and the bulk of
 * the output stays in the files that hold it. A run that ran out of time carries
 * one timeout record beside that evidence: which limit expired, in which phase,
 * and whether the harness could confirm that the execution it stopped really
 * ended. A run stopped by its caller carries one cancellation record of its own
 * instead, in the same shape and with the same limitation stated: a stop that
 * could not be confirmed leaves a working copy that may still be written to, and
 * a report that did not say so would invite reusing it.
 *
 * Beside the evidence, every report carries one change summary: what the retained
 * working copy differs from its recorded base by, which of those paths touch
 * tests, tooling, or configuration, and the two statements a reader must not be
 * left to assume — that `passed` means the configured checks passed, and that a
 * flagged path is one to look at rather than one the harness has judged
 * (docs/spec.md §5). {@link summarizeChanges} is that summary, and it records an
 * inspection that could not be made as such, never as an empty one. It is written
 * once, and
 * only for a run that got as far as a run directory: an invocation refused
 * before that has nothing to report and is a CLI error instead. See
 * docs/spec.md §§3–5.
 */

import { createWriteStream } from 'node:fs';
import { appendFile, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import type { WriteStream } from 'node:fs';
import type {
  AttemptEvidence,
  AttemptKind,
  CancellationEvidence,
  ChangedPath,
  ChangeSummary,
  CheckRoundResult,
  CommandResult,
  RunReport,
  RunStatus,
  TimeoutEvidence,
  WorkspaceReport,
} from './types.js';
import type { PreparedWorkspace, RunDirectory, SourcePreflight } from './workspace.js';

/** A log file that could not be created, written, or appended to. */
export class ReportError extends Error {
  constructor(message: string, options?: { cause?: unknown }) {
    super(message, options);
    this.name = 'ReportError';
  }
}

/** Name of the append-only lifecycle timeline inside `logs/`. */
const RUN_LOG_NAME = 'run.log';

/** Name of the final report inside the run directory. */
const RUN_REPORT_NAME = 'result.json';

/**
 * Log file names are generated by the harness, but a value that could be read
 * as a path is refused rather than rewritten: a label never decides where a run
 * writes.
 */
const LOG_LABEL_PATTERN = /^[A-Za-z0-9][A-Za-z0-9_.-]{0,63}$/;

function messageOf(cause: unknown): string {
  return cause instanceof Error ? cause.message : String(cause);
}

/** The lifecycle timeline of a run: `<logsDir>/run.log`. */
export function runLogPath(logsDir: string): string {
  return path.join(logsDir, RUN_LOG_NAME);
}

/**
 * Appends one timestamped line to the run timeline, creating the file when it
 * does not exist yet. Earlier lines are never rewritten, so the timeline reads
 * in the order the run produced it.
 */
export async function appendRunLog(runLog: string, message: string): Promise<void> {
  if (message.trim() === '' || /[\r\n]/.test(message)) {
    throw new ReportError(
      `"${message}" is not a usable timeline message. The timeline holds one line per state ` +
        'change, so a message must be nonblank and must not contain a line break.',
    );
  }

  try {
    await appendFile(runLog, `${new Date().toISOString()} ${message}\n`, 'utf8');
  } catch (cause) {
    throw new ReportError(
      `the run timeline "${runLog}" could not be appended to: ${messageOf(cause)}`,
      { cause },
    );
  }
}

/** The two output files of one configured command invocation. */
export interface CommandLog {
  readonly stdoutPath: string;
  readonly stderrPath: string;
  /** Adds a chunk of the command's standard output. */
  writeStdout(chunk: string): void;
  /** Adds a chunk of the command's standard error. */
  writeStderr(chunk: string): void;
  /**
   * Flushes and closes both files. Rejects with a {@link ReportError} when the
   * output could not be written: a result whose evidence was lost must not be
   * reported as a usable one.
   */
  close(): Promise<void>;
}

/**
 * Creates one file exclusively, so a file that is already there is never
 * overwritten. `whenTaken` says what the taken name means for the caller.
 */
async function createFileExclusively(file: string, whenTaken: string): Promise<void> {
  try {
    await writeFile(file, '', { flag: 'wx' });
  } catch (cause) {
    if ((cause as NodeJS.ErrnoException).code === 'EEXIST') {
      throw new ReportError([`"${file}" already exists.`, whenTaken].join('\n'), { cause });
    }
    throw new ReportError(`"${file}" could not be created: ${messageOf(cause)}`, { cause });
  }
}

/** Why a taken command-log name is refused rather than reused. */
const COMMAND_LOG_TAKEN = [
  'A command name is used once per run, and the logs of earlier commands are kept as they',
  'are: they are never truncated or overwritten.',
].join('\n');

/** Resolves when the stream has finished and closed, or already had. */
function endStream(stream: WriteStream): Promise<void> {
  return new Promise((resolve) => {
    if (stream.closed || stream.destroyed) {
      resolve();
      return;
    }
    stream.once('close', () => resolve());
    stream.end();
  });
}

/**
 * Creates the output files of one command invocation: `<label>.stdout.log` and
 * `<label>.stderr.log` in `logsDir`. The caller writes the command's output
 * into them and closes them before reading the result.
 */
export async function openCommandLog(logsDir: string, label: string): Promise<CommandLog> {
  if (!LOG_LABEL_PATTERN.test(label)) {
    throw new ReportError(
      [
        `"${label}" is not a usable log label.`,
        'A label is a short name of letters, digits, "_", "-", and "." that identifies this',
        "invocation's two log files. It never names a path, so it cannot decide where a run writes.",
      ].join('\n'),
    );
  }

  const stdoutPath = path.join(logsDir, `${label}.stdout.log`);
  const stderrPath = path.join(logsDir, `${label}.stderr.log`);
  await createFileExclusively(stdoutPath, COMMAND_LOG_TAKEN);
  await createFileExclusively(stderrPath, COMMAND_LOG_TAKEN);

  const streams: WriteStream[] = [];
  let failed: string | null = null;

  // Writes happen while the command runs, so a stream error is remembered for
  // close() instead of becoming an unhandled 'error' event.
  const appendStream = (file: string): WriteStream => {
    const stream = createWriteStream(file, { flags: 'a', encoding: 'utf8' });
    stream.on('error', (cause: unknown) => {
      failed ??= messageOf(cause);
    });
    streams.push(stream);
    return stream;
  };

  const stdout = appendStream(stdoutPath);
  const stderr = appendStream(stderrPath);
  let closed = false;

  return {
    stdoutPath,
    stderrPath,
    writeStdout: (chunk: string) => {
      stdout.write(chunk);
    },
    writeStderr: (chunk: string) => {
      stderr.write(chunk);
    },
    close: async () => {
      if (closed) {
        return;
      }
      closed = true;
      await Promise.all(streams.map(endStream));
      if (failed !== null) {
        throw new ReportError(
          `the output of "${label}" could not be written to "${logsDir}": ${failed}`,
        );
      }
    },
  };
}

/** How much of one output file a repair turn is given, in characters. */
const OUTPUT_EXCERPT_LIMIT = 4000;

/** Marks an excerpt that left earlier output out. */
const OUTPUT_OMITTED = '… (earlier output omitted)\n';

/** What an invocation that wrote nothing is recorded as, in feedback. */
const OUTPUT_EMPTY = '(no output was written)';

/**
 * The end of one log file, bounded. The end is the interesting part: a command
 * reports the failure after the work that led to it. A file this run's own
 * command wrote and that cannot be read now contributes nothing — the path is
 * still recorded in the command result, so nothing is hidden by that.
 */
async function readOutputTail(file: string): Promise<string> {
  let text: string;
  try {
    text = await readFile(file, 'utf8');
  } catch {
    return '';
  }
  if (text.length <= OUTPUT_EXCERPT_LIMIT) {
    return text.trimEnd();
  }
  return OUTPUT_OMITTED + text.slice(text.length - OUTPUT_EXCERPT_LIMIT).trimEnd();
}

/**
 * What one command invocation wrote, as far as it was recorded: its standard
 * output and its standard error, each labelled with the log file it came from and
 * bounded to the end of that file. This is the failure output a repair turn is
 * given (docs/spec.md §2). It is a copy for that turn; the files themselves stay
 * where they are, unchanged.
 */
export async function readCommandOutput(result: CommandResult): Promise<string> {
  const stdout = await readOutputTail(result.stdoutPath);
  const stderr = await readOutputTail(result.stderrPath);
  return [
    `stdout (${result.stdoutPath}):`,
    stdout === '' ? OUTPUT_EMPTY : stdout,
    `stderr (${result.stderrPath}):`,
    stderr === '' ? OUTPUT_EMPTY : stderr,
  ].join('\n');
}

/** Why a taken agent-log name is refused rather than reused. */
const AGENT_LOG_TAKEN = [
  'Each top-level coding turn writes its own agent log, and the output of an earlier turn is',
  'kept as it is: it is never truncated or overwritten.',
].join('\n');

/** The file holding the useful output of one top-level coding turn. */
export interface AgentLog {
  /** The file this turn's output goes to. Referenced by the report, never copied in. */
  readonly path: string;
  /** Adds a chunk of the agent's useful output. */
  write(chunk: string): void;
  /**
   * Flushes and closes the file. Rejects with a {@link ReportError} when the
   * output could not be written: a turn whose evidence was lost must not be
   * reported as a usable one.
   */
  close(): Promise<void>;
}

/**
 * Turns are counted from 1: turn 1 is the implementation, and every turn after
 * it is a repair. A turn number is generated by the caller's own loop, so a
 * value that could name something else is refused rather than used.
 */
function assertUsableTurn(turn: number): void {
  if (Number.isInteger(turn) && turn >= 1) {
    return;
  }
  throw new ReportError(
    `"${String(turn)}" is not a usable coding turn: turns are counted from 1, where turn 1 is the ` +
      'implementation and the repair turns follow it.',
  );
}

/**
 * The agent log of top-level coding turn `turn`: `agent-implementation.log` for
 * the implementation, then `agent-repair-1.log`, `agent-repair-2.log`, … for the
 * repairs. Each turn has its own file, so no turn can overwrite another's
 * output, and the report points at these files instead of holding transcripts.
 */
export function agentLogPath(logsDir: string, turn: number): string {
  assertUsableTurn(turn);
  const name = turn === 1 ? 'agent-implementation' : `agent-repair-${String(turn - 1)}`;
  return path.join(logsDir, `${name}.log`);
}

/**
 * Creates the log of one coding turn. The caller writes the turn's useful output
 * into it and closes it, and keeps the returned path for the report.
 */
export async function openAgentLog(logsDir: string, turn: number): Promise<AgentLog> {
  const file = agentLogPath(logsDir, turn);
  await createFileExclusively(file, AGENT_LOG_TAKEN);

  const stream = createWriteStream(file, { flags: 'a', encoding: 'utf8' });
  let failed: string | null = null;
  stream.on('error', (cause: unknown) => {
    failed ??= messageOf(cause);
  });
  let closed = false;

  return {
    path: file,
    write: (chunk: string) => {
      stream.write(chunk);
    },
    close: async () => {
      if (closed) {
        return;
      }
      closed = true;
      await endStream(stream);
      if (failed !== null) {
        throw new ReportError(
          `the agent output of coding turn ${String(turn)} could not be written to "${file}": ${failed}`,
        );
      }
    },
  };
}

/**
 * The only final statuses a run has (docs/spec.md §3). Checked at run time as
 * well as in the type, because a status that arrived from somewhere untyped must
 * not become a fourth one in a report.
 */
const FINAL_STATUSES: ReadonlySet<string> = new Set(['passed', 'failed', 'cancelled']);

/** Why a taken report name is refused rather than reused. */
const REPORT_TAKEN = [
  'A run writes one final report, and an existing one is evidence of an earlier finalization:',
  'it is left exactly as it is.',
].join('\n');

/**
 * What a `passed` run means, and what it does not (docs/spec.md §5). It is
 * written once here so the run timeline and the report cannot drift into saying
 * different things, and so neither can be read as a stronger claim than the
 * checks the harness really ran: the configured post-agent checks exiting `0` is
 * evidence about those commands, not proof of the task and not a safety verdict.
 */
const CHECKS_WARNING = [
  '`passed` means the configured post-agent checks exited successfully for the retained working copy.',
  'It does not prove that every acceptance criterion is met, and it does not mean the change is safe to',
  'ship: review the diff before delivery.',
].join(' ');

/**
 * Why the flagged paths need a human look. The harness points at them; it does
 * not read them, and it does not enforce anything about them (docs/spec.md §5).
 */
const HIGHLIGHTED_WARNING = [
  'the flagged paths change tests, tooling, or configuration, so the checks that decided this run may',
  'not be the checks the task needed. The harness flags them; it does not judge them, and it does not',
  'enforce tamper-proof tests.',
].join(' ');

/**
 * What a change summary is built from: the paths a working-copy inspection found,
 * or why the inspection could not be made. Exactly one of the two, because a
 * summary that could not be taken has nothing to list and must not read as one
 * that found nothing (docs/spec.md §5).
 */
export type ChangeSummaryRequest =
  | {
      /** The recorded base commit the paths were compared against. */
      readonly baseCommit: string;
      /** Every path that differs from the base, as the inspection found it. */
      readonly paths: readonly ChangedPath[];
    }
  | {
      /** The recorded base commit the comparison would have been made against. */
      readonly baseCommit: string;
      /** Why the comparison was not made, in one sentence. Never blank. */
      readonly problem: string;
    };

/**
 * The final summary of what a run left in its working copy, with the two
 * statements a reader must not be left to assume: what the run's status proves,
 * and why the flagged paths need looking at.
 *
 * A comparison that was not made keeps the reason and lists nothing, which is the
 * one thing it must not be confused with: a working copy that really matched its
 * base. {@link ChangeSummary.inspected} is what tells the two apart, and it is
 * set only for a summary built from a real inspection.
 */
export function summarizeChanges(request: ChangeSummaryRequest): ChangeSummary {
  const problem = 'problem' in request ? request.problem : null;
  const paths = 'paths' in request ? request.paths : [];
  const highlighted = paths.filter((entry) => entry.categories.length > 0);

  return {
    baseCommit: request.baseCommit,
    inspected: problem === null,
    problem,
    paths,
    highlighted,
    warnings: {
      checks: CHECKS_WARNING,
      highlighted: highlighted.length === 0 ? null : HIGHLIGHTED_WARNING,
    },
  };
}

/** What the caller asks a final report to record. */
export interface RunReportRequest {
  /** The allocated run directory: run ID, layout, and log directory. */
  readonly run: RunDirectory;
  /** The task the run was asked to complete, as a label. */
  readonly task: { readonly id: string; readonly title: string };
  /** The repository and committed base the run was approved against. */
  readonly source: SourcePreflight;
  /**
   * The prepared working copy, or `null` when preparation failed. The run
   * directory exists either way: preparation can fail after it was created, and
   * the report then records the facts it has and says what is missing instead of
   * describing a clone that was never made.
   */
  readonly workspace: PreparedWorkspace | null;
  /** Why there is no usable working copy; `null` exactly when `workspace` is not. */
  readonly preparationProblem: string | null;
  /** Start of the run, as an ISO timestamp. */
  readonly startedAt: string;
  /** End of the run, as an ISO timestamp. */
  readonly endedAt: string;
  /** How the run ended: one of {@link RunStatus}, and nothing else. */
  readonly status: RunStatus;
  /** Why it ended that way, in one sentence. Never blank. */
  readonly reason: string;
  /** The baseline round, or `null` when no baseline round was observed. */
  readonly baseline: CheckRoundResult | null;
  /** One entry per top-level coding turn, oldest first. */
  readonly attempts: readonly AttemptEvidence[];
  /**
   * What stopped the run when its time ran out: which limit expired, in which
   * phase, and whether the harness confirmed that the execution it stopped
   * really ended. `null` for a run that ended for any other reason.
   */
  readonly timeout: TimeoutEvidence | null;
  /**
   * What stopped a run its caller cancelled: in which phase it was stopped, and
   * whether the harness confirmed that the execution it stopped really ended.
   * `null` for a run that ended for any other reason — including a run that
   * ends as `cancelled` without a stop to describe, which is why this is
   * optional rather than required of that status.
   */
  readonly cancellation?: CancellationEvidence | null;
  /**
   * What the retained working copy differs from its recorded base by, and what a
   * reader must not conclude from the status above; see {@link ChangeSummary}.
   * Required of every run: a run whose working copy could not be compared with
   * its base says so here, rather than reporting no changes.
   */
  readonly changes: ChangeSummary;
}

/** Refuses a request that would describe a run other than the one that happened. */
function assertReportable(request: RunReportRequest): void {
  if (!FINAL_STATUSES.has(request.status)) {
    throw new ReportError(
      `"${String(request.status)}" is not a final run status: a run ends as "passed", "failed", or ` +
        '"cancelled", and nothing else (docs/spec.md §3).',
    );
  }

  if (request.reason.trim() === '') {
    throw new ReportError(
      'a report needs a reason: say in one sentence why the run ended the way it did.',
    );
  }

  const hasWorkspace = request.workspace !== null;
  const hasProblem = request.preparationProblem !== null;
  if (hasWorkspace === hasProblem) {
    throw new ReportError(
      hasWorkspace
        ? 'a prepared working copy and a preparation problem cannot both be recorded: the report ' +
            'would describe a working copy that also failed to be prepared.'
        : 'a report without a prepared working copy has to say why one is missing. Preparation can ' +
            'fail after the run directory exists, and the directory alone is not a working copy.',
    );
  }

  for (const [index, attempt] of request.attempts.entries()) {
    const turn = index + 1;
    const kind: AttemptKind = turn === 1 ? 'implementation' : 'repair';
    if (attempt.turn !== turn || attempt.kind !== kind) {
      throw new ReportError(
        `coding turn ${String(turn)} is not recorded as such: attempts are recorded in order, and ` +
          `turn ${String(turn)} is ${turn === 1 ? 'the implementation' : 'a repair'} (received ` +
          `turn ${String(attempt.turn)}, kind "${attempt.kind}").`,
      );
    }
    if (attempt.agentLog.trim() === '') {
      throw new ReportError(
        `coding turn ${String(turn)} has no agent log: every turn keeps its useful output in its ` +
          'own file, and the report points at it rather than copying it in.',
      );
    }
  }

  if (request.timeout !== null) {
    const { timeout } = request;
    if (request.status !== 'failed') {
      throw new ReportError(
        `a timeout is reported as "failed", not as "${request.status}": an expired limit is not a red ` +
          'check round to repair, and it is certainly not a pass (docs/spec.md §3).',
      );
    }
    const unconfirmed = timeout.termination !== 'confirmed';
    if (unconfirmed === (timeout.problem === null)) {
      throw new ReportError(
        unconfirmed
          ? 'a timeout whose termination is unconfirmed has to say what could not be confirmed: the ' +
              "limitation belongs in the report rather than in a reader's assumptions about what is " +
              'still running.'
          : 'a timeout with a confirmed termination has nothing left to explain, so it cannot also ' +
              'carry a problem: the report would describe a stop that both did and did not happen.',
      );
    }
  }

  const cancellation = request.cancellation ?? null;
  if (cancellation !== null) {
    if (request.status !== 'cancelled') {
      throw new ReportError(
        `a run that its caller stopped is reported as "cancelled", not as "${request.status}": a ` +
          'stop that came from outside the run is not a red check round to repair, and it is ' +
          'certainly not a pass (docs/spec.md §3).',
      );
    }
    const unconfirmed = cancellation.termination !== 'confirmed';
    if (unconfirmed === (cancellation.problem === null)) {
      throw new ReportError(
        unconfirmed
          ? 'a cancellation whose termination is unconfirmed has to say what could not be confirmed: ' +
              'the limitation belongs in the report rather than in an assumption that the working ' +
              'copy it was writing to is safe to reuse.'
          : 'a cancellation with a confirmed termination has nothing left to explain, so it cannot ' +
              'also carry a problem: the report would describe a stop that both did and did not ' +
              'happen.',
      );
    }
  }

  const { changes } = request;
  if (changes.inspected && changes.problem !== null) {
    throw new ReportError(
      'a change summary that was inspected has nothing left to explain, so it cannot also carry a ' +
        'problem: the report would describe a working copy that both was and was not compared with ' +
        'its base.',
    );
  }
  if (!changes.inspected && changes.problem === null) {
    throw new ReportError(
      'a change summary that was not inspected has to say why: a run whose working copy could not be ' +
        'compared with its recorded base must never read as one that left no changes.',
    );
  }
  if (!changes.inspected && (changes.paths.length > 0 || changes.highlighted.length > 0)) {
    throw new ReportError(
      'a change summary that was not inspected cannot list changed paths: nothing was read, so a list ' +
        'of paths would describe a comparison that never happened.',
    );
  }
  if (changes.baseCommit !== request.source.baseCommit) {
    throw new ReportError(
      `the change summary is recorded against ${changes.baseCommit}, not against the base this run ` +
        `recorded (${request.source.baseCommit}): every path in it is a difference from the recorded ` +
        'base, and a summary against another commit describes another run.',
    );
  }

  const stoppedUnconfirmed =
    request.timeout?.termination === 'unconfirmed' ||
    request.cancellation?.termination === 'unconfirmed';
  if (stoppedUnconfirmed && changes.inspected) {
    throw new ReportError(
      'the run ended without confirming that everything it had started had stopped, so its working ' +
        'copy cannot be summarized as final: something may still be writing to it, and the report has ' +
        'to record why the summary is unavailable instead.',
    );
  }

  const last = request.attempts.at(-1) ?? null;
  if (request.status === 'passed' && last?.checks?.outcome !== 'passed') {
    throw new ReportError(
      [
        'a report cannot say the run passed: the checks observed after the last coding turn are not',
        'a completed green round. `passed` means every configured post-agent check exited',
        'successfully for the retained working copy (docs/spec.md §3). What the agent said about its',
        'own turn is not a check result.',
      ].join('\n'),
    );
  }
}

/** The working copy as the report records it, prepared or not. */
function workspaceReport(request: RunReportRequest): WorkspaceReport {
  const { workspace } = request;
  if (workspace === null) {
    return {
      path: request.run.workspacePath,
      prepared: false,
      branch: null,
      problem: request.preparationProblem,
    };
  }
  return {
    path: workspace.workspacePath,
    prepared: true,
    branch: workspace.branch,
    problem: null,
  };
}

/** The final report of a run: `<runDir>/result.json`. */
export function runReportPath(runDir: string): string {
  return path.join(runDir, RUN_REPORT_NAME);
}

/**
 * Writes the final report of one run and returns the file it wrote, so a caller
 * never has to guess where the report is. A report is written once: an existing
 * `result.json` is refused rather than overwritten, because it is evidence of an
 * earlier finalization.
 *
 * Everything that goes wrong here is a {@link ReportError} naming the file, and
 * nothing is returned for a report that was not written: a caller cannot
 * announce a report location that does not exist. Where the report is printed is
 * the caller's business.
 */
export async function writeRunReport(request: RunReportRequest): Promise<string> {
  const report = buildReport(request);
  const file = runReportPath(request.run.runDir);

  try {
    // `wx`: the file is created by this call, so a report that is already there
    // — evidence of an earlier finalization — is never overwritten.
    await writeFile(file, `${JSON.stringify(report, null, 2)}\n`, { flag: 'wx', encoding: 'utf8' });
  } catch (cause) {
    if ((cause as NodeJS.ErrnoException).code === 'EEXIST') {
      throw new ReportError([`"${file}" already exists.`, REPORT_TAKEN].join('\n'), { cause });
    }
    throw new ReportError(`the report "${file}" could not be written: ${messageOf(cause)}`, {
      cause,
    });
  }

  return file;
}

/** The report of one run, validated and ready to serialize. */
function buildReport(request: RunReportRequest): RunReport {
  assertReportable(request);
  return {
    runId: request.run.runId,
    task: { id: request.task.id, title: request.task.title },
    source: { path: request.source.sourceRoot, baseCommit: request.source.baseCommit },
    workspace: workspaceReport(request),
    startedAt: request.startedAt,
    endedAt: request.endedAt,
    status: request.status,
    reason: request.reason,
    repairsUsed: request.attempts.filter((attempt) => attempt.kind === 'repair').length,
    baseline: request.baseline,
    attempts: request.attempts,
    timeout: request.timeout,
    cancellation: request.cancellation ?? null,
    changes: request.changes,
    runLog: runLogPath(request.run.logsDir),
  };
}
