/**
 * The log files one run writes under `<runDir>/logs`.
 *
 * Two kinds of file exist now, and nothing else:
 *
 * - `run.log`, one append-only human-readable timeline of the run's meaningful
 *   state changes (preparation, baseline, agent turns, check rounds, repairs,
 *   cancellation, final status). It is a debugging aid, not a logging
 *   subsystem: no levels, no structured events, no log library. Command output
 *   is never copied into it.
 * - One `.stdout.log`/`.stderr.log` pair per configured command invocation, so
 *   each command's output stays separate, identifiable, and complete.
 *
 * Files are created exclusively and only appended to afterwards: evidence from
 * an earlier invocation is never truncated or overwritten. The final
 * `result.json` report is a later task; this module owns only these log files.
 */

import { createWriteStream } from 'node:fs';
import { appendFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import type { WriteStream } from 'node:fs';

/** A log file that could not be created, written, or appended to. */
export class ReportError extends Error {
  constructor(message: string, options?: { cause?: unknown }) {
    super(message, options);
    this.name = 'ReportError';
  }
}

/** Name of the append-only lifecycle timeline inside `logs/`. */
const RUN_LOG_NAME = 'run.log';

/**
 * Log file names are generated by the harness, but a value that could be read
 * as a path is refused rather than rewritten: a label never decides where a run
 * writes.
 */
const LOG_LABEL_PATTERN = /^[A-Za-z0-9][A-Za-z0-9_.-]{0,63}$/;

function messageOf(cause: unknown): string {
  return cause instanceof Error ? cause.message : String(cause);
}

/** The lifecycle timeline of a run: `<logsDir>/run.log`. */
export function runLogPath(logsDir: string): string {
  return path.join(logsDir, RUN_LOG_NAME);
}

/**
 * Appends one timestamped line to the run timeline, creating the file when it
 * does not exist yet. Earlier lines are never rewritten, so the timeline reads
 * in the order the run produced it.
 */
export async function appendRunLog(runLog: string, message: string): Promise<void> {
  if (message.trim() === '' || /[\r\n]/.test(message)) {
    throw new ReportError(
      `"${message}" is not a usable timeline message. The timeline holds one line per state ` +
        'change, so a message must be nonblank and must not contain a line break.',
    );
  }

  try {
    await appendFile(runLog, `${new Date().toISOString()} ${message}\n`, 'utf8');
  } catch (cause) {
    throw new ReportError(
      `the run timeline "${runLog}" could not be appended to: ${messageOf(cause)}`,
      { cause },
    );
  }
}

/** The two output files of one configured command invocation. */
export interface CommandLog {
  readonly stdoutPath: string;
  readonly stderrPath: string;
  /** Adds a chunk of the command's standard output. */
  writeStdout(chunk: string): void;
  /** Adds a chunk of the command's standard error. */
  writeStderr(chunk: string): void;
  /**
   * Flushes and closes both files. Rejects with a {@link ReportError} when the
   * output could not be written: a result whose evidence was lost must not be
   * reported as a usable one.
   */
  close(): Promise<void>;
}

/** Creates one log file exclusively, so an earlier file is never overwritten. */
async function createLogFile(file: string): Promise<void> {
  try {
    await writeFile(file, '', { flag: 'wx' });
  } catch (cause) {
    if ((cause as NodeJS.ErrnoException).code === 'EEXIST') {
      throw new ReportError(
        [
          `"${file}" already exists.`,
          'A command name is used once per run, and the logs of earlier commands are kept as they',
          'are: they are never truncated or overwritten.',
        ].join('\n'),
        { cause },
      );
    }
    throw new ReportError(`"${file}" could not be created: ${messageOf(cause)}`, { cause });
  }
}

/** Resolves when the stream has finished and closed, or already had. */
function endStream(stream: WriteStream): Promise<void> {
  return new Promise((resolve) => {
    if (stream.closed || stream.destroyed) {
      resolve();
      return;
    }
    stream.once('close', () => resolve());
    stream.end();
  });
}

/**
 * Creates the output files of one command invocation: `<label>.stdout.log` and
 * `<label>.stderr.log` in `logsDir`. The caller writes the command's output
 * into them and closes them before reading the result.
 */
export async function openCommandLog(logsDir: string, label: string): Promise<CommandLog> {
  if (!LOG_LABEL_PATTERN.test(label)) {
    throw new ReportError(
      [
        `"${label}" is not a usable log label.`,
        'A label is a short name of letters, digits, "_", "-", and "." that identifies this',
        "invocation's two log files. It never names a path, so it cannot decide where a run writes.",
      ].join('\n'),
    );
  }

  const stdoutPath = path.join(logsDir, `${label}.stdout.log`);
  const stderrPath = path.join(logsDir, `${label}.stderr.log`);
  await createLogFile(stdoutPath);
  await createLogFile(stderrPath);

  const streams: WriteStream[] = [];
  let failed: string | null = null;

  // Writes happen while the command runs, so a stream error is remembered for
  // close() instead of becoming an unhandled 'error' event.
  const appendStream = (file: string): WriteStream => {
    const stream = createWriteStream(file, { flags: 'a', encoding: 'utf8' });
    stream.on('error', (cause: unknown) => {
      failed ??= messageOf(cause);
    });
    streams.push(stream);
    return stream;
  };

  const stdout = appendStream(stdoutPath);
  const stderr = appendStream(stderrPath);
  let closed = false;

  return {
    stdoutPath,
    stderrPath,
    writeStdout: (chunk: string) => {
      stdout.write(chunk);
    },
    writeStderr: (chunk: string) => {
      stderr.write(chunk);
    },
    close: async () => {
      if (closed) {
        return;
      }
      closed = true;
      await Promise.all(streams.map(endStream));
      if (failed !== null) {
        throw new ReportError(
          `the output of "${label}" could not be written to "${logsDir}": ${failed}`,
        );
      }
    },
  };
}
